CREATE TABLE  SKU(
  ID INT PRIMARY KEY IDENTITY,
  Name NVARCHAR(20),
  Code AS ('s' + ID) PERSISTED UNIQUE  
)
CREATE TABLE  Family(
  ID INT PRIMARY KEY IDENTITY,
  SurName NVARCHAR(20),
  BudgetValue REAL 
)
CREATE TABLE  Basket(
  ID INT PRIMARY KEY IDENTITY,
  ID_SKU INT REFERENCES SKU (ID),
  ID_Family INT REFERENCES Family (ID),
  Quantity decimal CHECK(Quantity >0),
  Value decimal CHECK(Value >0), 
  PurchaseDate DATE DEFAULT GETDATE(), 
  DiscountValue REAL
)
